services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./clc3_project/prometheus:/etc/prometheus/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=200h'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./clc3_project/grafana/provisioning:/etc/grafana/provisioning
      - ./clc3_project/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - DISCORD_URL=https://discord.com/api/webhooks/1466838354145316925/EneSyH-WbHYhrPY54OJscf-4JcUj7O60KlAIpDDErlMSU7oVjtsC39TVZIxbT373IUMc
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: ticket-db-bottleneck
    restart: always
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: MyComplexPassword123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Allows you to connect from your laptop (localhost:5432)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'    # Limited to 25% of one CPU core
          memory: 256M
    # Healthcheck ensures FastAPI waits until DB is actually ready
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myadmin -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: ticket-system-web
    ports:
      - "8000:8000"
    environment:
      # Notice the host is 'db', matching the service name above
      DATABASE_URL: postgresql://myadmin:MyComplexPassword123!@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  prometheus_data:
  grafana_data:
  postgres_data: