apiVersion: 1
contactPoints:
  - orgId: 1
    name: 'Discord-Notifications'
    receivers:
      - uid: 'discord_alert_receiver' # Moved inside receivers
        type: discord
        settings:
          url: ${DISCORD_URL}
          message: |
            @everyone 
            **Alert:** {{ .CommonAnnotations.summary }}
            **Details:** {{ .CommonAnnotations.description }}