global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ticket_system'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['ticket-web:80']

#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'fastapi-app'
#    metrics_path: '/metrics'
#    static_configs:
#      - targets: ['host.docker.internal:8000']
#    scrape_interval: 5s