global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ticket_system'
    scrape_interval: 5s
    static_configs:
      # In K8s, use the Service Name 'ticket-web' and the Service Port '80'
      # (Use 80 because your Service maps port 80 -> targetPort 8000)
      - targets: ['ticket-web:80']